<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video.js HLS Quality Test</title>

    <!-- 1. Include Video.js CSS -->
    <link href="https://vjs.zencdn.net/8.10.0/video-js.css" rel="stylesheet" />
    <!-- Optional: Include a theme for a nicer look -->
    <link href="https://unpkg.com/@videojs/themes@1/dist/city/index.css" rel="stylesheet">


    <style>
        body { font-family: sans-serif; background-color: #f0f2f5; margin: 0; padding: 20px; display: flex; flex-direction: column; align-items: center; }
        .video-container { max-width: 800px; width: 100%; margin-top: 20px; box-shadow: 0 4px 12px rgba(0,0,0,0.15); }
    </style>
</head>
<body>

    <h1>Video Player with Quality Selector</h1>

    @if(session('success'))
        <div style="padding: 15px; margin-bottom: 20px; border-radius: 4px; width: 100%; max-width: 770px; box-sizing: border-box; background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb;">
            {{ session('success') }}
        </div>
    @endif

    <div class="video-container">
        {{-- The video tag is now simpler. No <source> tag. We will add it via JavaScript. --}}
        {{-- Added the 'vjs-theme-city' class for a nicer theme --}}
        <video id="my-player" class="video-js vjs-theme-city vjs-big-play-centered" controls preload="auto"></video>
    </div>
    
    <p style="margin-top: 20px; font-size: 0.9em; color: #666;">Loading video from: <code>{{ $videoUrl }}</code></p>
    
    <!-- 2. Include Video.js JavaScript -->
    <script src="https://vjs.zencdn.net/8.10.0/video.min.js"></script>

    <!-- 3. Include the HLS Quality Selector Plugin -->
    <script src="https://cdn.jsdelivr.net/npm/videojs-hls-quality-selector@1.1.4/dist/videojs-hls-quality-selector.min.js"></script>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // 4. Get the video source URL generated by Laravel
            const videoSrc = @json($videoUrl);

            // 5. Define the player options in an object
            const options = {
                controls: true,
                autoplay: 'muted',
                preload: 'auto',
                fluid: true, // Makes the player responsive
                sources: [{ // Set the source directly in the options
                    src: videoSrc,
                    type: 'application/x-mpegURL'
                }],
                plugins: {
                    // This is the most reliable way to enable the plugin
                    hlsQualitySelector: {
                        displayCurrentQuality: true, // Optional: Shows the current quality (e.g., 720p)
                    }
                }
            };

            // 6. Initialize the Video.js player with the options
            const player = videojs('my-player', options);

            player.ready(function() {
                console.log('Player is ready.');
                // At this point, the player, the plugin, and the source are all loaded together.
            });
        });
    </script>

</body>
</html>